# Generated by Django 6.0.5 on 2026-05-18 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('muscle_growth', 'Muscle Growth'), ('daily_habits', 'Improve Daily Habits'), ('lose_fat', 'Lose Fat'), ('flexibility', 'Flexibility'), ('strength_training', 'Strength Training'), ('core', 'Core'), ('running', 'Running')], max_length=20)),
                ('duration_minutes', models.IntegerField(choices=[(15, '15 minutes / day'), (30, '30 minutes / day'), (60, '1 hour / day')])),
                ('intensity', models.IntegerField()),
                ('bmi_at_creation', models.FloatField(blank=True, null=True)),
                ('daily_calories', models.IntegerField(default=0)),
                ('workout_plan', models.JSONField(default=dict)),
                ('nutrition_plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
