# Generated by Django 4.2.30 on 2026-05-18 05:38

import json
from django.db import migrations, models


def goals_to_json(apps, schema_editor):
    WeeklyPlan = apps.get_model('plans', 'WeeklyPlan')
    for plan in WeeklyPlan.objects.all():
        raw = plan.goal
        if isinstance(raw, str):
            try:
                parsed = json.loads(raw)
                plan.goal = parsed if isinstance(parsed, list) else [parsed]
            except (json.JSONDecodeError, TypeError):
                plan.goal = [raw] if raw else []
            # Write back as JSON string directly so SQLite is happy before schema change
            schema_editor.connection.cursor().execute(
                "UPDATE plans_weeklyplan SET goal = %s WHERE id = %s",
                [json.dumps(plan.goal), plan.pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(goals_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weeklyplan',
            name='goal',
            field=models.JSONField(default=list),
        ),
    ]
