# Generated by Django 4.2.30 on 2026-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_weeklyplan_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='completions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
