# Generated by Django 4.2.30 on 2026-05-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_duration',
            field=models.IntegerField(blank=True, choices=[(15, '15 minutes / day'), (30, '30 minutes / day'), (60, '1 hour / day')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_goal',
            field=models.CharField(blank=True, choices=[('muscle_growth', 'Muscle Growth'), ('daily_habits', 'Improve Daily Habits'), ('lose_fat', 'Lose Fat'), ('flexibility', 'Flexibility'), ('strength_training', 'Strength Training'), ('core', 'Core'), ('running', 'Running')], max_length=20),
        ),
    ]
