# Generated by Django 4.2.30 on 2026-05-18 05:38

import json
from django.db import migrations, models


def preferred_goal_to_json(apps, schema_editor):
    db = schema_editor.connection
    rows = db.cursor().execute("SELECT id, preferred_goal FROM tracker_userprofile").fetchall()
    for pk, raw in rows:
        if raw is None:
            continue
        try:
            parsed = json.loads(raw)
            new_val = parsed if isinstance(parsed, list) else [parsed]
        except (json.JSONDecodeError, TypeError, ValueError):
            new_val = [raw] if raw else []
        db.cursor().execute(
            "UPDATE tracker_userprofile SET preferred_goal = %s WHERE id = %s",
            [json.dumps(new_val), pk],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile_preferred_duration_and_more'),
    ]

    operations = [
        migrations.RunPython(preferred_goal_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_goal',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
