# Generated by Django 4.2.30 on 2026-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_userprofile_preferred_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_weight_kg',
            field=models.FloatField(blank=True, help_text='Goal weight in kg', null=True),
        ),
    ]
